name: portfolio
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bubble_tab_indicator: "^0.1.4"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-ExtraLight-Italic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Light.ttf
          weight: 200
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Light-Italic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-SemiLight.ttf
          weight: 300
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-SemiLight-Italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Italic.ttf
          style: italic
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Medium-Italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Bold-Italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-ExtraBold-Italic.ttf
          weight: 800
          style: italic  
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Thin.ttf
          weight: 100
        - asset: assets/fonts/Raleway/Raleway-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Raleway/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Raleway/Raleway-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway/Raleway-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway/Raleway-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway/Raleway-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway/Raleway-BlackItalic.ttf
          weight: 900
          style: italic
